[Fixes #2] falscher user bei servicectl stop btcontrol

diff --git a/etc/init.d/btcontrol b/etc/init.d/btcontrol
--- a/etc/init.d/btcontrol
+++ b/etc/init.d/btcontrol
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+# !!!hint!!!
+#   mit systemd sieht man echo's bei journalctl -f
+#   will man bluetooth verwendenen dann bei Required-Start: bluetooth hinzufügen
+
 ### BEGIN INIT INFO
 # Provides:          btcontrol
 # Required-Start:    avahi networking $remote_fs $syslog
@@ -66,17 +70,24 @@ case $1 in
 		;;
 	stop)
 		# Stop the daemon.
+		log_daemon_msg "stopping  the process" "$NAME" "pidfile: $PIDFILE"
 		if [ -e $PIDFILE ]; then
 			status_of_proc -p $PIDFILE $DAEMON "Stoppping the $NAME process" && status="0" || status="$?"
 			if [ "$status" = 0 ]; then
-				start-stop-daemon --stop --quiet --oknodo --user $USER --pidfile $PIDFILE --retry=TERM/10/KILL/5
-				/bin/rm -rf $PIDFILE
+				if [ "$CHUSER" ] ; then
+					args="--user $CHUSER "
+				fi
+				start-stop-daemon --stop  --oknodo $args --pidfile $PIDFILE --retry=TERM/10/KILL/5
+				ret=$?
+				#/bin/rm -rf $PIDFILE
 			fi
 		else
 			log_daemon_msg "$NAME process is not running"
 			log_end_msg 0
 		fi
 		killall initbtrail.sh
+		# wenns initbtrail nicht mehr rennt macht das exit code 3
+		exit $ret
 		;;
 	restart)
 		# Restart the daemon.
